// <auto-generated />
namespace YourPlace.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCOMMENTentitycreateoneotmanyrelationwithRESTAURANTentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCOMMENTentitycreateoneotmanyrelationwithRESTAURANTentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201812022227400_Add COMMENT entity, create one ot many relation with RESTAURANT entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
